# Generated by Django 4.0.1 on 2022-01-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_player_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="classroom",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="level",
            field=models.IntegerField(null=True),
        ),
    ]
