# Generated by Django 4.0.1 on 2022-02-03 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_tournament_started_tournamentplayer_kicked_out_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixture",
            name="level",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="fixture",
            name="tournament",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.tournament",
            ),
        ),
    ]
