# Generated by Django 4.0.1 on 2022-02-04 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_fixture_options_fixture_level_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixture',
            options={'ordering': ['-level_number', 'tournament']},
        ),
    ]
