# Generated by Django 4.0.1 on 2022-02-04 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_fixture_dependent_on"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fixture",
            name="dependent_on",
        ),
        migrations.AddField(
            model_name="fixture",
            name="root",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="app.fixture",
            ),
        ),
    ]
