# Generated by Django 4.0.1 on 2022-02-08 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_remove_fixture_root"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixture",
            name="root",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="app.fixture",
            ),
        ),
    ]
