# Generated by Django 4.0.1 on 2022-02-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_game_unique_together_game_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='minutes_per_player',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('fixture', 'time')},
        ),
    ]
