# Generated by Django 4.0.1 on 2022-02-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_game_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
