# Generated by Django 4.0.1 on 2022-02-12 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_fixture_finished"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixture",
            name="winner",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="app.player"
            ),
        ),
    ]
