# Generated by Django 4.0.1 on 2022-02-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0024_fixture_winner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fixture",
            name="winner",
        ),
        migrations.AddField(
            model_name="playerfixture",
            name="is_winner",
            field=models.BooleanField(default=False),
        ),
    ]
