# Generated by Django 4.0.1 on 2022-02-13 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0025_remove_fixture_winner_playerfixture_is_winner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerfixture",
            name="color",
        ),
        migrations.AddField(
            model_name="playerfixture",
            name="tournamentplayer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.tournamentplayer",
            ),
        ),
    ]
