# Generated by Django 4.0.1 on 2022-02-13 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0026_remove_playerfixture_color_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="playerfixture",
            unique_together={("tournamentplayer", "fixture")},
        ),
        migrations.RemoveField(
            model_name="playerfixture",
            name="player",
        ),
    ]
