# Generated by Django 4.0.1 on 2022-02-25 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0029_alter_fixture_tournament_alter_playerfixture_player"),
    ]

    operations = [
        migrations.CreateModel(
            name="TournamentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_points_for_draw", models.FloatField()),
                ("number_of_points_for_win", models.FloatField()),
                ("number_of_points_for_loss", models.FloatField()),
                ("name", models.CharField(max_length=50, unique=True)),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.AddField(
            model_name="player",
            name="image",
            field=models.ImageField(default="", upload_to=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tournament",
            name="image",
            field=models.ImageField(default="", upload_to=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tournament",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="app.tournamentcategory",
            ),
        ),
    ]
