# Generated by Django 4.0.1 on 2022-03-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_fixture_options_alter_game_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixture',
            options={'ordering': ['-level_number', 'tournament'], 'verbose_name': 'Fixture', 'verbose_name_plural': 'Fixtures'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['time'], 'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Player', 'verbose_name_plural': 'Players'},
        ),
        migrations.AlterModelOptions(
            name='playerfixture',
            options={'verbose_name': 'Fixture player', 'verbose_name_plural': 'Fixture players'},
        ),
        migrations.AlterModelOptions(
            name='playerfixturegame',
            options={'verbose_name': 'Fixture game result', 'verbose_name_plural': 'Fixture game results'},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'verbose_name': 'Tournament', 'verbose_name_plural': 'Tournaments'},
        ),
        migrations.AlterModelOptions(
            name='tournamentcategory',
            options={'verbose_name': 'Tournament category', 'verbose_name_plural': 'Tournament categories'},
        ),
        migrations.AlterModelOptions(
            name='tournamentplayer',
            options={'verbose_name': 'Tournament participant', 'verbose_name_plural': 'Tournament participants'},
        ),
        migrations.AddField(
            model_name='tournamentplayer',
            name='rating',
            field=models.FloatField(default=800),
        ),
    ]
