# Generated by Django 4.0.1 on 2022-03-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0034_alter_fixture_options_alter_game_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="telegram_username",
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
    ]
