# Generated by Django 4.0.1 on 2022-03-21 20:16

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_player_telegram_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='terms',
            field=models.FileField(blank=True, null=True, upload_to=app.models.tournament_directory_path),
        ),
    ]
