# Generated by Django 4.0.1 on 2022-03-24 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_tournament_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.fixture'),
        ),
    ]
