# Generated by Django 4.0.1 on 2022-03-29 08:12

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_player_gender_alter_player_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='level_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='level_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='name_fr',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='terms_en',
            field=models.FileField(blank=True, null=True, upload_to=app.models.tournament_directory_path),
        ),
        migrations.AddField(
            model_name='tournament',
            name='terms_fr',
            field=models.FileField(blank=True, null=True, upload_to=app.models.tournament_directory_path),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.tournament_directory_path),
        ),
        migrations.AlterField(
            model_name='tournamentcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
