# Generated by Django 4.0.1 on 2022-04-08 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_tournamentplayer_player'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tournamentplayer',
            unique_together=set(),
        ),
    ]
